version: 2
jobs:
    build:
        working_directory: /go/src/github.com/kai-zoa/loport
        docker:
            - image: golang:latest
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: "loport"
                command: |
                    go get -u github.com/golang/dep/...
                    dep ensure
                    go build -a -o loport ./*.go
